### ISSUE TITLE
Migrate to Django 1.9

### ISSUE THREAD

**Issue by fosskers** [CSSS/old-csss-site#17]
We get the following when running our 1.8 code with 1.9:

```
/usr/lib/python3.5/site-packages/django_markdown/urls.py:8: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  '', url('preview/$', preview, name='django_markdown_preview'))
```

**Comment by fosskers** [comment]
Note that the `django_markdown` package doesn't work with 1.9. Please review the possibility of migration in August 2016.

**Comment by asabaya3** [comment]
@fosskers  did you mean 1.9? 
Also, 'django_markdown' had not been updated in a year. The possibility of future compatibility is low.

**Comment by fosskers** [comment]
Yeah, fixed it.

**Comment by fosskers** [comment]
I think there is a competitor package.
