### ISSUE TITLE
Site Improvement Suggestions

### ISSUE THREAD

**Issue by fosskers** [CSSS/old-csss-site#18]
Feel free to discuss potential site improvements here.

**Comment by baconator** [comment]
Perhaps adding Vim, Django and CLion to the software page would be useful?

**Comment by fosskers** [comment]
Thanks! I rewrote the page with (nearly) pure Markdown, and added sections on Vim and Django. I left out CLion, as we don't advise using IDEs.

**Comment by baconator** [comment]
Fair enough; figured it was a long shot anyhow. Thank you for adding the rest!

**Comment by modernNeo** [comment]
anyone here know the creds to our sfucsss.org site?

**Comment by fosskers** [comment]
Do you mean the login to the admin panel? The droplet? The namecheap account?

**Comment by modernNeo** [comment]
whichever is the access for updating the execs on that site

**Comment by modernNeo** [comment]
they're really out of date and no process has been established for maintaining the site so i figured i'd get something started in that sense

**Comment by fosskers** [comment]
Sounds like people dropped the ball in the credentials hand-off.

**Comment by modernNeo** [comment]
Yea, are you able to help with this, You still have the info?

**Comment by modernNeo** [comment]
i was able to get help elsewhere, never mind

**Comment by fosskers** [comment]
Could you write here what the problem and solution was? Did you get access to the admin panel?

Documenting these things leaves a nice paper trail for people in the future.

**Comment by modernNeo** [comment]
The problem was just that a proper hand-off of the credentials never happened between the old president and the new one. I was able to get in touch with the previous president and have him help me regain access to the admin panel.

**Comment by modernNeo** [comment]
Hi Corbett, please check gitter
